Remove Travis CI config and documentation references
pytest-dev/cookiecutter-pytest-plugin pull request #56
Opened 2021-09-24 00:56 UTC by ronnie-llamado

This removes `.travis.yml` and Travis CI documentation references.

Resolves #55

2021-09-24 10:44 UTC, nicoddemus approved these changes

2021-09-28 09:22 UTC, hackebrot requested changes
Hi @ronnie-llamado! 👋🏻 

Thanks so much for submitting a pull request for this! Your contribution is very much appreciated.

There should be one more mention of `Travis CI` on `README.md` in the features section. If you could remove that too, that'd be great. 🤖

2021-09-28 16:20 UTC, ronnie-llamado commented
Always glad to contribute @hackebrot! 

See the most recent commit for requested changes.

2021-09-30 06:07 UTC, hackebrot approved these changes
LGTM! 🚀

2021-09-30 06:10 UTC, merged